[build]
builder = "nixpacks"
buildCommand = "python3 -m venv /opt/venv && . /opt/venv/bin/activate && pip3 install -r requirements.txt"

[deploy]
startCommand = ". /opt/venv/bin/activate && python3 run_bot.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 