[build]
builder = "nixpacks"
buildCommand = "python -m venv /opt/venv && . /opt/venv/bin/activate && pip install -r requirements.txt"

[deploy]
startCommand = "python main.py"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10 